name: Compiler le jeu Nintendo DS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Construire l'environnement DS
        run: docker build -t badtimeds-builder .

      - name: Compiler le jeu
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/source" \
            -w /source \
            badtimeds-builder \
            make -j$(nproc)

      - name: Récupérer le fichier NDS
        uses: actions/upload-artifact@v4
        with:
          name: badtimeds-nds
          path: "*.nds"
