name: Compiler le jeu Nintendo DS

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer les outils Nintendo DS
        run: dkp-pacman -S --noconfirm nds-dev

      - name: Compiler
        run: make -j$(nproc)

      - name: Sauvegarder le fichier NDS
        uses: actions/upload-artifact@v4
        with:
          name: badtimeds-nds
          path: "*.nds"
